#!/usr/bin/env python3
"""Generates firmware/src/pukcc_vector.h - one fixed RSA-2048 key plus a raw
private-operation test vector, so 'pukcc_bench' on the board can check that the
accelerator returned the RIGHT answer and not merely a fast one.

Run from the repo root:  .venv/Scripts/python.exe scripts/gen_pukcc_vector.py
Regenerating changes the key; nothing else in the project depends on it.
"""
import random
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

random.seed(20260908)
key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
pn = key.private_numbers()
n = key.public_key().public_numbers().n
der = key.private_bytes(serialization.Encoding.DER,
                        serialization.PrivateFormat.TraditionalOpenSSL,   # PKCS#1
                        serialization.NoEncryption())

x = int.from_bytes(bytes(random.randrange(256) for _ in range(256)), "big") % n
y = pow(x, pn.d, n)
assert pow(y, 65537, n) == x, "vector does not round-trip"


def c_bytes(name, data):
    lines = ["    " + " ".join("0x%02X," % b for b in data[i:i + 12])
             for i in range(0, len(data), 12)]
    return "static const uint8_t %s[%d] = {\n%s\n};\n" % (name, len(data), "\n".join(lines))


parts = ['''/*
 * pukcc_vector.h - generated by scripts/gen_pukcc_vector.py, do not hand-edit.
 *
 * A throwaway RSA-2048 key (PKCS#1 DER) and one raw private-key operation on
 * it: y = x^d mod n. This board never uses this key for anything - its only
 * job is to let 'pukcc_bench' verify the accelerator's arithmetic. That check
 * is the point: a wrong Crypto RAM layout produces a fast WRONG answer, which
 * a timing-only benchmark would happily report as a 14x speed-up.
 *
 * The round trip (y^e mod n == x) was verified on the host at generation time.
 */
#ifndef PUKCC_VECTOR_H
#define PUKCC_VECTOR_H

#include <stdint.h>
''']
parts.append(c_bytes("PUKCC_VEC_KEY_DER", der))
parts.append(c_bytes("PUKCC_VEC_X", x.to_bytes(256, "big")))
parts.append(c_bytes("PUKCC_VEC_Y", y.to_bytes(256, "big")))
parts.append("\n#endif /* PUKCC_VECTOR_H */\n")
open("firmware/src/pukcc_vector.h", "w", encoding="utf-8", newline="\n").write("\n".join(parts))
print("wrote firmware/src/pukcc_vector.h  (DER %d bytes)" % len(der))
